{{- if .Values.authenticatedEmailsFile.enabled }}
{{- if and (.Values.authenticatedEmailsFile.restricted_access) (eq .Values.authenticatedEmailsFile.persistence "configmap")  }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
{{- if .Values.authenticatedEmailsFile.annotations }}
  annotations:
{{ toYaml .Values.authenticatedEmailsFile.annotations | indent 4 }}
{{- end }}
  name: {{ template "oauth2-proxy.fullname" . }}-accesslist
data:
  restricted_user_access: {{ .Values.authenticatedEmailsFile.restricted_access | quote }}
{{- end }}
{{- end }}
