{{- if not .Values.config.existingConfig }}
{{- if .Values.config.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
data:
  oauth2_proxy.cfg: {{ .Values.config.configFile | quote }}
{{- end }}
{{- end }}
