{{- if and (eq .Values.sessionStorage.type "redis") (not .Values.sessionStorage.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-redis-access
type: Opaque
data:
  redis-password: {{ .Values.sessionStorage.redis.password | b64enc | quote }}
  redis-sentinel-password: {{ .Values.sessionStorage.redis.sentinel.password | b64enc | quote }}
{{- end -}}
